language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install: "pip install -r requirements.txt"

script:
- pytest
- coverage run tests.py

#install:
#  - pip install codecov

after_success:
  - codecov