sudo: false
language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
 - "pip install -r requirements.txt"
 - "pip install tox-travis"

script:
- tox
- coverage run tests.py
#script: tox

#install:
#  - pip install codecov

after_success:
  - codecov